name: Build GhostLock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27b

      - name: Compile Binary
        run: |
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang -O3 src/*.c -o ghostlock

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ghostlock-binary
          path: ghostlock

